using System.Collections;
using UnityEngine;
using EndlessEngine.ClickLoop;
using EndlessEngine.Config;
using EndlessEngine.Input;

namespace EndlessEngine.Bootstrap
{
    /// <summary>
    /// Wires and starts the Click active-loop sub-system generated by New Game Wizard.
    ///
    /// Attach alongside AutoSetupBootstrap. Runs after IsReady.
    /// ClickLoopService detects clicks via IInputProvider, raycasts for ClickTargets,
    /// and awards gold with combo/crit mechanics.
    ///
    /// ClickTarget world objects must exist in the scene with a Collider2D
    /// (SceneSetupUtility creates them automatically for ClickLoop game type).
    /// </summary>
    [DefaultExecutionOrder(-490)]
    [AddComponentMenu("Endless Engine/Click Loop Bootstrap")]
    public class ClickLoopBootstrap : MonoBehaviour
    {
        [SerializeField] private ClickLoopConfigSO  _clickConfig;
        [SerializeField] private InputProviderUnity _inputProvider;
        [SerializeField] private LayerMask          _clickTargetLayer;

        private IEnumerator Start()
        {
            var bootstrap = GetComponent<AutoSetupBootstrap>();
            if (bootstrap != null)
                yield return new WaitUntil(() => bootstrap.IsReady);

            if (_inputProvider == null)
                _inputProvider = gameObject.AddComponent<InputProviderUnity>();

            if (_clickConfig == null)
            {
                Debug.LogWarning("[ClickLoopBootstrap] No ClickLoopConfigSO assigned. Using defaults.");
                _clickConfig = ScriptableObject.CreateInstance<ClickLoopConfigSO>();
            }

            var clickService = gameObject.AddComponent<ClickLoopService>();
            clickService.Initialize(
                config:      _clickConfig,
                economy:     bootstrap?.Economy,
                input:       _inputProvider,
                targetLayer: _clickTargetLayer,
                statistics:  null,
                vfx:         null);

            if (bootstrap?.Save != null)
                bootstrap.Save.RegisterStateProvider(clickService);

            clickService.OnYieldAwarded += gold =>
                Debug.Log($"[ClickLoopBootstrap] Click gold: +{gold:F0}");

            Debug.Log("[ClickLoopBootstrap] Click loop started. Click the targets!");
        }
    }
}
