using System.Collections;
using UnityEngine;
using UnityEngine.UI;
using EndlessEngine.Economy;
using EndlessEngine.Generator;
using EndlessEngine.Harvest;
using EndlessEngine.ClickLoop;
using EndlessEngine.Wave;
using EndlessEngine.Research;
using EndlessEngine.UI;

namespace EndlessEngine.Bootstrap
{
    /// <summary>
    /// Runtime HUD controller for scenes generated by New Game Wizard.
    ///
    /// Finds all UI GameObjects by name and subscribes to engine events automatically.
    /// Supports all game types: Pure Idle, Clicker, Click Loop, Harvest, Wave/RPG,
    /// Tower Defense, Merge, Farm, Research, Building, Prestige-Heavy.
    ///
    /// Named GameObjects it looks for (all optional):
    ///   GoldLabel, IncomeLabel, GeneratorCountLabel, GeneratorTitle
    ///   BuyGeneratorButton, PrestigeButton, PrestigeLabel, SaveLabel
    ///   WaveLabel, EnemyCountLabel
    ///   HarvestLabel, ComboLabel
    ///   ClickIncomeLabel
    ///   GemLabel, ResearchLabel
    /// </summary>
    [AddComponentMenu("Endless Engine/Generated Game HUD")]
    public class GeneratedGameHUD : MonoBehaviour
    {
        [Tooltip("Bootstrap GameObject that owns AutoSetupBootstrap (auto-found if null).")]
        [SerializeField] private GameObject _bootstrapSource;

        private AutoSetupBootstrap _bootstrap;

        // UI element cache
        private Component _goldLabel;
        private Component _incomeLabel;
        private Component _generatorCountLabel;
        private Component _prestigeLabel;
        private Component _saveLabel;
        private Component _waveLabel;
        private Component _enemyCountLabel;
        private Component _harvestLabel;
        private Component _comboLabel;
        private Component _clickIncomeLabel;
        private Component _gemLabel;
        private Component _researchLabel;
        private Button    _buyGeneratorButton;
        private Button    _prestigeButton;
        private Button    _upgradesButton;

        private float  _saveTimer;
        private double _lastGold;
        private float  _incomeClock;
        private double _harvestTotal;
        private long   _clickTotal;

        private IEnumerator Start()
        {
            if (_bootstrapSource != null)
                _bootstrap = _bootstrapSource.GetComponent<AutoSetupBootstrap>();
            if (_bootstrap == null)
                _bootstrap = FindFirstObjectByType<AutoSetupBootstrap>();

            if (_bootstrap == null)
            {
                Debug.LogWarning("[GeneratedGameHUD] AutoSetupBootstrap not found.");
                yield break;
            }

            yield return new WaitUntil(() => _bootstrap.IsReady);

            // Find UI elements
            _goldLabel           = FindLabel("GoldLabel");
            _incomeLabel         = FindLabel("IncomeLabel");
            _generatorCountLabel = FindLabel("GeneratorCountLabel");
            _prestigeLabel       = FindLabel("PrestigeLabel");
            _saveLabel           = FindLabel("SaveLabel");
            _waveLabel           = FindLabel("WaveLabel");
            _enemyCountLabel     = FindLabel("EnemyCountLabel");
            _harvestLabel        = FindLabel("HarvestLabel");
            _comboLabel          = FindLabel("ComboLabel");
            _clickIncomeLabel    = FindLabel("ClickIncomeLabel");
            _gemLabel            = FindLabel("GemLabel");
            _buyGeneratorButton  = FindButton("BuyGeneratorButton");
            _prestigeButton      = FindButton("PrestigeButton");
            _upgradesButton      = FindButton("UpgradesButton");
            _researchLabel       = FindLabel("ResearchLabel");

            // Subscribe to events
            EconomyService.OnResourcesChanged    += HandleGoldChanged;
            GeneratorSystem.OnGeneratorPurchased += HandleGeneratorPurchased;
            WaveSpawnManager.OnWaveStarted       += HandleWaveStarted;
            ResearchService.OnNodeCompleted      += HandleResearchNodeCompleted;
            ResearchService.OnResearchProgress   += HandleResearchProgress;

            // Harvest events — subscribe if HarvestLoopService present in scene
            var harvestSvc = FindFirstObjectByType<HarvestLoopService>();
            if (harvestSvc != null)
            {
                harvestSvc.OnYieldAwarded  += HandleHarvestYield;
                harvestSvc.OnComboChanged  += HandleComboChanged;
            }

            // Click loop events — subscribe if ClickLoopService present
            var clickSvc = FindFirstObjectByType<ClickLoopService>();
            if (clickSvc != null)
            {
                clickSvc.OnYieldAwarded += HandleClickYield;
                clickSvc.OnComboChanged += HandleComboChanged;
            }

            // Buttons
            _buyGeneratorButton?.onClick.AddListener(OnBuyGenerator);
            _prestigeButton?.onClick.AddListener(OnPrestige);

            // Wire Upgrades button → UpgradeScreenController.Show() + inject EconomyService
            var upgradeScreen = FindFirstObjectByType<EndlessEngine.UI.UpgradeScreenController>();
            if (upgradeScreen != null)
            {
                upgradeScreen.InjectEconomy(_bootstrap.Economy);
                if (_upgradesButton != null)
                    _upgradesButton.onClick.AddListener(upgradeScreen.Show);
            }

            // Initial state
            SetText(_goldLabel, "Gold: 0");
            SetText(_incomeLabel, "Income: 0/s");
            _lastGold = _bootstrap.Economy?.CurrentResources ?? 0;
        }

        private void OnDestroy()
        {
            EconomyService.OnResourcesChanged    -= HandleGoldChanged;
            GeneratorSystem.OnGeneratorPurchased -= HandleGeneratorPurchased;
            WaveSpawnManager.OnWaveStarted       -= HandleWaveStarted;
            ResearchService.OnNodeCompleted      -= HandleResearchNodeCompleted;
            ResearchService.OnResearchProgress   -= HandleResearchProgress;

            var harvestSvc = FindFirstObjectByType<HarvestLoopService>();
            if (harvestSvc != null) { harvestSvc.OnYieldAwarded -= HandleHarvestYield; harvestSvc.OnComboChanged -= HandleComboChanged; }

            var clickSvc = FindFirstObjectByType<ClickLoopService>();
            if (clickSvc != null) { clickSvc.OnYieldAwarded -= HandleClickYield; clickSvc.OnComboChanged -= HandleComboChanged; }
        }

        private void Update()
        {
            if (_bootstrap == null) return;

            // 1-second income rate
            _incomeClock += Time.deltaTime;
            if (_incomeClock >= 1f)
            {
                double cur  = _bootstrap.Economy?.CurrentResources ?? 0;
                double rate = cur - _lastGold;
                _lastGold   = cur;
                _incomeClock = 0f;
                SetText(_incomeLabel, $"Income: {Fmt(rate)}/s");
            }

            // Save indicator fade
            if (_saveTimer > 0)
            {
                _saveTimer -= Time.deltaTime;
                if (_saveTimer <= 0) SetText(_saveLabel, "");
            }

            // Generator button affordability + label
            RefreshGeneratorButton();
        }

        // ── Event handlers ────────────────────────────────────────────────────────

        private void HandleGoldChanged(double current, double delta)
        {
            SetText(_goldLabel, $"Gold: {Fmt(current)}");
            if (_generatorCountLabel != null && _bootstrap?.Generators != null)
                SetText(_generatorCountLabel, $"Owned: {_bootstrap.Generators.TotalGeneratorsOwned()}");
        }

        private void HandleGeneratorPurchased(string id)
        {
            if (_generatorCountLabel != null && _bootstrap?.Generators != null)
                SetText(_generatorCountLabel, $"Owned: {_bootstrap.Generators.TotalGeneratorsOwned()}");
            ShowSaveIndicator("Saved");
        }

        private void HandleWaveStarted(int wave)
        {
            SetText(_waveLabel, $"Wave: {wave}");
        }

        private void HandleHarvestYield(float amount)
        {
            _harvestTotal += amount;
            SetText(_harvestLabel, $"Harvested: {Fmt(_harvestTotal)}");
        }

        private void HandleComboChanged(float combo)
        {
            SetText(_comboLabel, $"Combo: ×{combo:F1}");
        }

        private void HandleClickYield(float amount)
        {
            _clickTotal += (long)amount;
            SetText(_clickIncomeLabel, $"Click gold: {Fmt(_clickTotal)}");
        }

        private void HandleResearchProgress(string treeId, string nodeId, int tick, int total)
        {
            SetText(_researchLabel, $"Research: {nodeId}  {tick}/{total}");
        }

        private void HandleResearchNodeCompleted(string treeId, string nodeId)
        {
            SetText(_researchLabel, $"✓ {nodeId} done!");
            ShowSaveIndicator("Saved");
        }

        // ── Button handlers ───────────────────────────────────────────────────────

        private void OnBuyGenerator()
        {
            if (_bootstrap?.Generators == null) return;
            var cfgs = _bootstrap.Generators.Configs;
            if (cfgs != null && cfgs.Count > 0)
            {
                bool ok = _bootstrap.Generators.TryPurchase(cfgs[0].GeneratorId);
                if (ok) ShowSaveIndicator("Saving...");
            }
        }

        private void OnPrestige()
        {
            var pm = FindFirstObjectByType<EndlessEngine.Prestige.PrestigeStateManager>();
            if (pm != null && pm.CanPrestige)
            {
                pm.TryPrestige();
                ShowSaveIndicator("Prestige!");
            }
            else
            {
                Debug.Log("[GeneratedGameHUD] Prestige not available yet.");
            }
        }

        private void RefreshGeneratorButton()
        {
            if (_buyGeneratorButton == null) return;
            if (_bootstrap?.Generators == null || _bootstrap?.Economy == null) return;
            var cfgs = _bootstrap.Generators.Configs;
            if (cfgs == null || cfgs.Count == 0) return;

            string id   = cfgs[0].GeneratorId;
            double cost = _bootstrap.Generators.GetNextCost(id);
            _buyGeneratorButton.interactable = _bootstrap.Economy.CurrentResources >= cost;

            string lbl = $"Buy {cfgs[0].DisplayName} ({Fmt(cost)})";
            var txt = _buyGeneratorButton.GetComponentInChildren<Text>();
            if (txt != null) txt.text = lbl;
#if TMPRO_PRESENT
            var tmp = _buyGeneratorButton.GetComponentInChildren<TMPro.TextMeshProUGUI>();
            if (tmp != null) tmp.text = lbl;
#endif
        }

        private void ShowSaveIndicator(string msg)
        {
            SetText(_saveLabel, msg);
            _saveTimer = 2f;
        }

        // ── UI helpers ────────────────────────────────────────────────────────────

        private static string Fmt(double v)
        {
            if (v >= 1e15) return $"{v / 1e15:0.#}Qa";
            if (v >= 1e12) return $"{v / 1e12:0.#}T";
            if (v >= 1e9)  return $"{v / 1e9:0.#}B";
            if (v >= 1e6)  return $"{v / 1e6:0.#}M";
            if (v >= 1e3)  return $"{v / 1e3:0.#}K";
            return ((long)v).ToString();
        }

        private static Component FindLabel(string name)
        {
            var go = GameObject.Find(name);
            if (go == null) return null;
#if TMPRO_PRESENT
            var t = go.GetComponent<TMPro.TextMeshProUGUI>();
            if (t != null) return t;
#endif
            return go.GetComponent<Text>();
        }

        private static Button FindButton(string name)
        {
            var go = GameObject.Find(name);
            return go != null ? go.GetComponent<Button>() : null;
        }

        private static void SetText(Component c, string text)
        {
            if (c == null) return;
#if TMPRO_PRESENT
            if (c is TMPro.TextMeshProUGUI t) { t.text = text; return; }
#endif
            if (c is Text txt) txt.text = text;
        }
    }
}
