using System.Collections;
using UnityEngine;
using UnityEngine.UI;
using EndlessEngine.Economy;
using EndlessEngine.Generator;
using EndlessEngine.Wave;

namespace EndlessEngine.Bootstrap
{
    /// <summary>
    /// Runtime HUD controller generated by New Game Wizard's scene builder.
    ///
    /// Finds all named UI elements in the scene by name and wires them to the
    /// economy/generator events. No Inspector references required — works with
    /// any scene structure built by SceneSetupUtility.
    ///
    /// Compatible with both legacy Unity UI Text and TextMeshPro.
    /// </summary>
    [AddComponentMenu("Endless Engine/Generated Game HUD")]
    public class GeneratedGameHUD : MonoBehaviour
    {
        [Tooltip("Bootstrap GameObject that owns AutoSetupBootstrap (auto-found if null).")]
        [SerializeField] private GameObject _bootstrapSource;

        private AutoSetupBootstrap _bootstrap;

        // Cached UI elements (found by name at startup)
        private Component _goldLabel;
        private Component _incomeLabel;
        private Component _generatorCountLabel;
        private Component _prestigeLabel;
        private Component _saveLabel;
        private Component _waveLabel;
        private Component _enemyCountLabel;
        private Button    _buyGeneratorButton;
        private Button    _prestigeButton;

        private float _saveIndicatorTimer;
        private double _lastGold;
        private double _goldLastSecond;
        private float  _incomeAvgTimer;

        private IEnumerator Start()
        {
            // Find bootstrap
            if (_bootstrapSource != null)
                _bootstrap = _bootstrapSource.GetComponent<AutoSetupBootstrap>();
            if (_bootstrap == null)
                _bootstrap = FindFirstObjectByType<AutoSetupBootstrap>();

            if (_bootstrap == null)
            {
                Debug.LogWarning("[GeneratedGameHUD] AutoSetupBootstrap not found in scene.");
                yield break;
            }

            // Wait for bootstrap to finish
            yield return new WaitUntil(() => _bootstrap.IsReady);

            // Find UI elements by name
            _goldLabel           = FindLabel("GoldLabel");
            _incomeLabel         = FindLabel("IncomeLabel");
            _generatorCountLabel = FindLabel("GeneratorCountLabel");
            _prestigeLabel       = FindLabel("PrestigeLabel");
            _saveLabel           = FindLabel("SaveLabel");
            _waveLabel           = FindLabel("WaveLabel");
            _enemyCountLabel     = FindLabel("EnemyCountLabel");
            _buyGeneratorButton  = FindButton("BuyGeneratorButton");
            _prestigeButton      = FindButton("PrestigeButton");

            // Subscribe to events
            EconomyService.OnResourcesChanged     += HandleGoldChanged;
            GeneratorSystem.OnGeneratorPurchased  += HandleGeneratorPurchased;
            WaveSpawnManager.OnWaveStarted        += HandleWaveStarted;

            // Wire buttons
            _buyGeneratorButton?.onClick.AddListener(OnBuyGenerator);
            _prestigeButton?.onClick.AddListener(OnPrestige);

            // Initial display
            SetText(_goldLabel, "Gold: 0");
            SetText(_incomeLabel, "Income: 0/s");

            _lastGold = _bootstrap.Economy?.CurrentResources ?? 0;
        }

        private void OnDestroy()
        {
            EconomyService.OnResourcesChanged    -= HandleGoldChanged;
            GeneratorSystem.OnGeneratorPurchased -= HandleGeneratorPurchased;
            WaveSpawnManager.OnWaveStarted       -= HandleWaveStarted;
        }

        private void Update()
        {
            // Income rate (moving average over 1s)
            _incomeAvgTimer += Time.deltaTime;
            if (_incomeAvgTimer >= 1f)
            {
                double current = _bootstrap?.Economy?.CurrentResources ?? 0;
                double rate    = current - _lastGold;
                _lastGold      = current;
                _incomeAvgTimer = 0f;
                SetText(_incomeLabel, $"Income: {FormatNumber(rate)}/s");
            }

            // Save indicator
            if (_saveIndicatorTimer > 0)
            {
                _saveIndicatorTimer -= Time.deltaTime;
                if (_saveIndicatorTimer <= 0)
                    SetText(_saveLabel, "");
            }

            // Generator button affordability
            RefreshGeneratorButton();
        }

        private void HandleGoldChanged(double current, double delta)
        {
            SetText(_goldLabel, $"Gold: {FormatNumber(current)}");

            if (_generatorCountLabel != null && _bootstrap?.Generators != null)
            {
                int total = _bootstrap.Generators.TotalGeneratorsOwned();
                SetText(_generatorCountLabel, $"Owned: {total}");
            }
        }

        private void HandleGeneratorPurchased(string id)
        {
            if (_generatorCountLabel != null && _bootstrap?.Generators != null)
            {
                int total = _bootstrap.Generators.TotalGeneratorsOwned();
                SetText(_generatorCountLabel, $"Owned: {total}");
            }
            SetText(_saveLabel, "Saving...");
            _saveIndicatorTimer = 2f;
        }

        private void HandleWaveStarted(int waveNumber)
        {
            SetText(_waveLabel, $"Wave: {waveNumber}");
        }

        private void OnBuyGenerator()
        {
            if (_bootstrap?.Generators == null) return;
            // Purchase the first available generator
            var configs = _bootstrap.Generators.Configs;
            if (configs != null && configs.Count > 0)
                _bootstrap.Generators.TryPurchase(configs[0].GeneratorId);
        }

        private void OnPrestige()
        {
            // PrestigeStateManager is not wired in AutoSetupBootstrap by default;
            // this is a placeholder for games that extend with prestige.
            Debug.Log("[GeneratedGameHUD] Prestige requested — wire PrestigeStateManager to enable.");
        }

        private void RefreshGeneratorButton()
        {
            if (_buyGeneratorButton == null) return;
            if (_bootstrap?.Generators == null || _bootstrap?.Economy == null) return;

            var configs = _bootstrap.Generators.Configs;
            if (configs == null || configs.Count == 0) return;

            string firstId = configs[0].GeneratorId;
            double cost    = _bootstrap.Generators.GetNextCost(firstId);
            bool   can     = _bootstrap.Economy.CurrentResources >= cost;
            _buyGeneratorButton.interactable = can;

            string label = $"Buy {configs[0].DisplayName} ({FormatNumber(cost)})";
            var txt = _buyGeneratorButton.GetComponentInChildren<Text>();
            if (txt != null) txt.text = label;
#if TMPRO_PRESENT
            var tmp = _buyGeneratorButton.GetComponentInChildren<TMPro.TextMeshProUGUI>();
            if (tmp != null) tmp.text = label;
#endif
        }

        // ── Helpers ───────────────────────────────────────────────────────────────

        private static string FormatNumber(double v)
        {
            if (v >= 1e15) return $"{v / 1e15:0.#}Qa";
            if (v >= 1e12) return $"{v / 1e12:0.#}T";
            if (v >= 1e9)  return $"{v / 1e9:0.#}B";
            if (v >= 1e6)  return $"{v / 1e6:0.#}M";
            if (v >= 1e3)  return $"{v / 1e3:0.#}K";
            return ((long)v).ToString();
        }

        private static Component FindLabel(string goName)
        {
            var go = GameObject.Find(goName);
            if (go == null) return null;
#if TMPRO_PRESENT
            var tmp = go.GetComponent<TMPro.TextMeshProUGUI>();
            if (tmp != null) return tmp;
#endif
            return go.GetComponent<Text>();
        }

        private static Button FindButton(string goName)
        {
            var go = GameObject.Find(goName);
            return go != null ? go.GetComponent<Button>() : null;
        }

        private static void SetText(Component c, string text)
        {
            if (c == null) return;
#if TMPRO_PRESENT
            if (c is TMPro.TextMeshProUGUI tmp) { tmp.text = text; return; }
#endif
            if (c is Text txt) txt.text = text;
        }
    }
}
