using System.Collections;
using UnityEngine;
using EndlessEngine.Config;
using EndlessEngine.Harvest;
using EndlessEngine.Input;

namespace EndlessEngine.Bootstrap
{
    /// <summary>
    /// Wires and starts the Harvest active-loop sub-system generated by New Game Wizard.
    ///
    /// Attach alongside AutoSetupBootstrap. Runs after IsReady.
    /// Creates HarvestCursor + HarvestLoopService + HarvestNodeSpawner programmatically
    /// using the configs assigned in the Inspector (auto-wired by SceneSetupUtility).
    ///
    /// The HarvestNodeSpawner spawns procedural placeholder nodes in the world
    /// (colored circles) so the game is immediately playable without custom art.
    /// </summary>
    [DefaultExecutionOrder(-490)]
    [AddComponentMenu("Endless Engine/Harvest Loop Bootstrap")]
    public class HarvestLoopBootstrap : MonoBehaviour
    {
        [SerializeField] private HarvestAreaConfigSO   _areaConfig;
        [SerializeField] private HarvestNodeConfigSO[] _nodeConfigs;
        [SerializeField] private InputProviderUnity    _inputProvider;

        private IEnumerator Start()
        {
            var bootstrap = GetComponent<AutoSetupBootstrap>();
            if (bootstrap != null)
                yield return new WaitUntil(() => bootstrap.IsReady);

            // Resolve input — use InputProviderUnity if assigned, else add one
            if (_inputProvider == null)
                _inputProvider = gameObject.AddComponent<InputProviderUnity>();

            // Create HarvestCursor
            var cursorGO = new GameObject("HarvestCursor");
            var cursor   = cursorGO.AddComponent<HarvestCursor>();
            cursor.Inject(_inputProvider);

            // Create HarvestLoopService
            var hlsGO   = new GameObject("HarvestLoopService");
            var harvest  = hlsGO.AddComponent<HarvestLoopService>();

            if (_areaConfig != null)
            {
                harvest.Initialize(
                    cursor:     cursor,
                    config:     _areaConfig,
                    economy:    bootstrap?.Economy,
                    statistics: null,
                    vfx:        null);
            }

            // Register with save
            if (bootstrap?.Save != null)
                bootstrap.Save.RegisterStateProvider(harvest);

            // Subscribe to events for feedback
            harvest.OnYieldAwarded += amount =>
                Debug.Log($"[HarvestLoopBootstrap] Yield: +{amount:F1} gold");

            Debug.Log("[HarvestLoopBootstrap] Harvest loop started. Move cursor over green nodes.");
        }
    }
}
