using UnityEngine;
using EndlessEngine.Economy;
using EndlessEngine.Config;

namespace EndlessEngine.Bootstrap
{
    /// <summary>
    /// Simple click handler for merge board cells generated by New Game Wizard.
    /// OnMouseDown selects this cell; a second click on a matching item triggers TryMerge.
    /// Requires a Camera with Physics2D raycasting enabled (default in 2D projects).
    /// </summary>
    [AddComponentMenu("Endless Engine/Merge Cell Handler")]
    public class MergeCellHandler : MonoBehaviour
    {
        // Item sitting in this cell (null = empty)
        private ItemConfigSO _item;
        private static MergeCellHandler _selected;

        public bool HasItem => _item != null;

        public void PlaceItem(ItemConfigSO item)
        {
            _item = item;
        }

        private void OnMouseDown()
        {
            var mergeService = FindFirstObjectByType<MergeService>();
            if (mergeService == null) return;

            if (_selected == null || _selected == this)
            {
                // First click — select this cell if it has an item
                if (_item != null)
                {
                    _selected = this;
                    Debug.Log($"[MergeCellHandler] Selected: {_item.ItemId}");
                }
                return;
            }

            // Second click — attempt merge between selected cell and this cell
            if (_selected._item != null && _item != null
                && _selected._item.MergeGroupId == _item.MergeGroupId
                && _selected._item.MergeTier    == _item.MergeTier)
            {
                var result = mergeService.TryMerge(_item);
                if (result.Success)
                {
                    _selected._item = null;
                    _item           = result.ResultItem;
                    Debug.Log($"[MergeCellHandler] Merged → {result.ResultItem?.ItemId}");
                }
                else
                {
                    Debug.Log($"[MergeCellHandler] Merge failed: {result.FailReason}");
                }
            }

            _selected = null;
        }
    }
}
