using System.Collections;
using UnityEngine;
using EndlessEngine.Config;
using EndlessEngine.Enemy;
using EndlessEngine.Wave;
using EndlessEngine.Combat;

namespace EndlessEngine.Bootstrap
{
    /// <summary>
    /// Wires and starts the wave/combat sub-system generated by New Game Wizard.
    ///
    /// Runs after AutoSetupBootstrap.IsReady. Uses null-safe stubs for IPlayerQuery
    /// and IDamageDispatcher so enemies spawn and move without a full player character.
    /// </summary>
    [DefaultExecutionOrder(-490)]
    [AddComponentMenu("Endless Engine/Wave Combat Bootstrap")]
    public class WaveCombatBootstrap : MonoBehaviour
    {
        [SerializeField] private WaveSpawnManager     _waveSpawnManager;
        [SerializeField] private EnemyManager         _enemyManager;
        [SerializeField] private AutoBattleController _autoBattle;
        [SerializeField] private WaveConfigSO         _waveConfig;
        [SerializeField] private EnemyStatConfigSO    _enemyConfig;

        private IEnumerator Start()
        {
            // Wait for AutoSetupBootstrap to complete its load sequence
            var bootstrap = GetComponent<AutoSetupBootstrap>();
            if (bootstrap != null)
                yield return new WaitUntil(() => bootstrap.IsReady);

            // Inject wave and enemy configs into ConfigRegistry
#if UNITY_EDITOR || DEVELOPMENT_BUILD
            ConfigRegistry.InjectForTesting(
                wave:  _waveConfig,
                enemy: _enemyConfig);
#endif

            // Stub IPlayerQuery — enemies target the world origin (0,0) if no player
            var playerStub = new StaticPlayerQuery(Vector2.zero);

            // Stub IDamageDispatcher — attacks are no-ops in the wizard-generated scene
            var dmgStub = new NoOpDamageDispatcher();

            // Initialize EnemyManager with stubs
            if (_enemyManager != null)
                _enemyManager.Initialize(playerStub, dmgStub);

            // Initialize WaveSpawnManager with save notifier (AutoSetupBootstrap.Save or stub)
            if (_waveSpawnManager != null)
            {
                IWaveSaveNotifier saveNotifier = bootstrap?.Save as IWaveSaveNotifier
                    ?? new NoOpWaveSaveNotifier();
                _waveSpawnManager.Initialize(_enemyManager, saveNotifier, healthSystem: null);
            }

            // Start first wave — enemies will spawn and move toward (0,0)
            if (_waveSpawnManager != null)
                _waveSpawnManager.StartFirstWave();

            Debug.Log("[WaveCombatBootstrap] Wave system started.");
        }

        // ── Null-object stubs ──────────────────────────────────────────────────────

        private class StaticPlayerQuery : IPlayerQuery
        {
            public Vector2 Position       { get; }
            public bool    IsInIdleRecovery => false;
            public StaticPlayerQuery(Vector2 pos) { Position = pos; }
        }

        private class NoOpDamageDispatcher : EndlessEngine.Enemy.IDamageDispatcher
        {
            public void DispatchEnemyAttack(EnemyAgent agent, Vector2 playerPosition) { }
        }

        private class NoOpWaveSaveNotifier : IWaveSaveNotifier
        {
            public void NotifyWaveMilestone(int waveNumber) { }
        }
    }
}
